server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Healthcheck (Render espera 200 em /api)
  location = /api {
    add_header Content-Type application/json;
    return 200 '{"status":"ok"}';
  }

  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
